#  🔀 Control Flow<br><br> ♻️ Loops and Conditional Statements

**The syntax for an ‘if' conditional statement is as follows:**

<pre>if (condition_1):<br>
    statement_block_1<br>
elif (condition_2):<br>
    statement_block_2<br>
elif (condition_3):<br>
    statement_block_3<br></pre>

### Control Flow - These decide what should run based on conditions.<br>
**if** - run a block if condition is true, checks a condition

**elif** - extra conditions

**else** - fallback, doesnt check a condition, default action when all conditions fail

**continue** - skip to next loop iteration

**break** - exit the loop completely

**Key rule:<br>
One : if per chain<br>
Zero or more : elif<br>
Zero or one : else**

### Basic If–Elif–Else Conditions

### Class Exercise 1

Write a Python program that checks the value of a variable score and prints:

"Outstanding" if the score is greater than 90

"Excellent" if the score is between 80 and 90

"Good" if the score is between 70 and 80

"You Need To Improve" for all other values, Assume score=88

In [1]:
score = 88

if score > 90:
    print("Outstanding")
elif score > 80 and score < 90:
    print("Excellent")
elif score > 70 and score < 80:
    print("Good")
else:
    print("You Need To Improve")

Excellent


### Class Exercise 2

Write a Python program that checks the current stock price stored in the variable stock_price and prints:

"We will buy 50 shares of ABC" if the price is less than 999

"We will buy 20 shares of ABC" if the price is exactly 1000

"We will buy 150 shares of ABC" if the price is greater than 1000

Assume stock_price = 1000.

In [2]:
stock_price = 1500  # then...

if (stock_price < 999):
    print("We will buy 50 shares of ABC")

elif (stock_price == 1000):
    print("We will buy 20 shares of ABC")

elif (stock_price > 1000):  
    print("We will buy 150 shares of ABC")

We will buy 150 shares of ABC


### Class Exercise 3

Write a Python program that checks the price of a stock stored in the variable stock_price_ABC and prints:

"We will sell the stock and book the profit" if the price is greater than 250

Otherwise, print "We will keep buying the stock"

Assume stock_price_ABC = 200.

In [3]:
stock_price_ABC = 200  # then...

if stock_price_ABC > 250:  # if condition 1 is false then....
    print("We will sell the stock and book the profit")

else:
    # this block of code will be executed
    print(" We will keep buying the stock")

 We will keep buying the stock


**A list contains many values, so you use a for loop to check each price one by one with the same if-elif logic.**

### Loop Through Lists & Apply Conditions

A loop statement allows us to execute a statement or group of statements multiple times.
The general syntax for a ‘for’ loop is : 
<pre>
<b>for (variable) in <b>sequence:
    block of statements</b>
</pre>

Here, the block of statements within the loop will get executed, until all ‘sequence’ elements get exhausted. Once all sequence elements are exhausted, the program will come out of the loop.

### Class Exercise 4

Write a Python program that loops through a list of stock prices and prints a trading action for each price based on the following rules:

If the price is less than 999, print:
"price → We will buy 50 shares of ABC"

If the price is exactly 1000, print:
"price → We will buy 20 shares of ABC"

If the price is greater than 1000, print:
"price → We will buy 150 shares of ABC"

Use the list:
prices = [995, 1000, 1020, 980, 1000, 1010]

In [4]:
prices = [995, 1000, 1020, 980, 1000, 1010]

for stock_price in prices:

    if stock_price < 999:
        print(stock_price, "→ We will buy 50 shares of ABC")

    elif stock_price == 1000:
        print(stock_price, "→ We will buy 20 shares of ABC")

    elif stock_price > 1000:
        print(stock_price, "→ We will buy 150 shares of ABC")

995 → We will buy 50 shares of ABC
1000 → We will buy 20 shares of ABC
1020 → We will buy 150 shares of ABC
980 → We will buy 50 shares of ABC
1000 → We will buy 20 shares of ABC
1010 → We will buy 150 shares of ABC


**all three (while, continue, break) belong to loops.**

### While Loop Example
**while → A type of loop**

It repeats as long as a condition stays true.

### Class Exercise 5

Write a Python program using a while loop that starts a counter at 0 and keeps printing the counter value as long as it is less than or equal to 5. After printing each value, increase the counter by 1.

In [5]:
import time

counter = 0

while counter <= 5:
    print(counter)
    counter += 1
    time.sleep(1)

0
1
2
3
4
5


✔ **continue → Skip the current iteration**

It jumps to the next loop cycle.

### Range Syntax : range(start, stop, step) - default start = 0, step = 1

### Class Exercise 6

Write a Python program that uses a for loop to print numbers from 1 to 5, but skip the number 3 using the continue statement.

In [6]:
for i in range(1, 6):
    if i == 3:
        continue  # skip 3
    print(i)

1
2
4
5


✔ **break → Stop the loop completely**

It exits the loop immediately, even if items are remaining.

### Class Exercise 7

Write a Python program that uses a for loop to print numbers from 1 onward, but stop the loop completely when the number becomes 3 using the break statement.

In [7]:
for i in range(1, 6):
    if i == 3:
        break  # stop at 3
    print(i)

1
2


**✔ Summary:<br>
while = loop that runs based on a condition<br>
continue = skip one iteration<br>
break = exit the loop fuly**<br>

### Example — Using while for Continuous Checking (simulation)

### Class Exercise 8

Write a Python program that starts with a stock price of 95 and keeps increasing it by 2 inside a while loop.<br>
As long as the price is less than the target price of 105, print the current price.<br>
Once the loop finishes, print "Target reached".

In [8]:
price = 95
target = 105

while price < target:
    print("Current price:", price)
    price += 2
print("Target reached")

Current price: 95
Current price: 97
Current price: 99
Current price: 101
Current price: 103
Target reached


### Class Exercise 9

Given a list of closing prices for a stock, write a Python program that loops through each price and prints:

"We Buy" if the price is less than 1200

"No new positions" if the price is exactly 1200

"We Sell" if the price is greater than 1200

After the loop ends, print "We are now out of the loop".

Use the price list:
Close_Price_Stock = [1000, 1010, 1200, 1250, 1200, 1300, 1397, 1400, 1425, 1410]

In [38]:
# Closing prices of the stock over a period

Close_Price_Stock = [1000, 1010, 1200, 1250, 1200,
                   1300, 1397, 1400, 1425, 1410]  # Our sequence

for i in Close_Price_Stock:

    if i < 1200:
        print("We Buy")

    elif i == 1200:
        print("No new positions")

    elif i > 1200:
        print("We Sell")

print("We are now out of the loop")

We Buy
We Buy
No new positions
We Sell
No new positions
We Sell
We Sell
We Sell
We Sell
We Sell
We are now out of the loop


**The variable ‘i’ first stores the value ‘1000’ in it and runs it through the loop to execute the statements. <br>
Now, ‘i’ will run through the sequence and pick the second element of the sequence which is ‘1010’.
<br>
Similarly, it will keep executing all the elements of the loop. Observe the output.**

### Class Exercise 10

Write a Python program that uses a while loop to start with x = 0 and keep increasing x by 1 on each iteration.<br>
As long as x is less than or equal to 15, print the value of x.<br>
After the loop finishes, print "We are now out of the loop".

In [10]:
x = 0

while x <=15:
    x = x + 1
    print(x)
print("We are now out of the loop")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
We are now out of the loop


### Class Exercise 11

Write a Python program that uses a for loop with range(1, 16, 2) to iterate through odd numbers from 1 to 15.<br>
Inside the loop, increase the value of x by 1 and print it.<br>
After the loop finishes, print "We are out of loop".

In [11]:
for x in range (1, 16, 2):
    x = x + 1
    print(x)
print("We are out of loop")

2
4
6
8
10
12
14
16
We are out of loop


### Append Values

### Class Exercise 12

Write a Python program that loops through a list of stock prices and uses append() to add trading signals to a new list called signal based on these rules:

If the price is greater than 70, append "buy" to the list

If the price is less than 70, append "sell" to the list

If the price is exactly 70, append "hold" to the list

Use the price list:
price = [70.2, 70, 80, 60.6]

Finally, print the signal list.

In [12]:
# Price of a stock
price = [70.2, 70, 80, 60.6]
signal = []

In [13]:
type(signal)

list

In [14]:
# Pay attention to the indentation and the syntax

for i in range(len(price)):
    
    if price[i]>70 :
        signal.append('buy')
    
    elif price[i]< 70:
        signal.append('sell')
        
    else:
        signal.append('hold')

In [15]:
print(signal)

['buy', 'hold', 'buy', 'sell']


### Looping Over Lists, Strings & Dictionaries

### Class Exercise 13

Create a list called top_gainers containing the stock names:
['BHARTIARTL', 'EICHERMOT', 'HCLTECH', 'BAJFINANCE', 'RELIANCE']

Write a Python program that loops through this list and prints each stock along with its index number.
Use the .index() method inside the print() statement to display the index.

In [16]:
top_gainers= ['BHARTIARTL', 'EICHERMOT', 'HCLTECH','BAJFINANCE', 'RELIANCE']

In [17]:
for i in top_gainers:
    print(top_gainers.index(i),  ' : ' , i)

0  :  BHARTIARTL
1  :  EICHERMOT
2  :  HCLTECH
3  :  BAJFINANCE
4  :  RELIANCE


.index() searches the list top_gainers<br>
It finds the position of the current value (gainer)<br>
And returns the index number (0, 1, 2, 3 …)

 **Strings in Python are iterable objects. In other words, strings are a sequence
 of characters. Hence, we can use a string as a sequence object in the for
 loop.**

In [18]:
program = "PYTHON"

for x in program:
    print(x)

P
Y
T
H
O
N


**Looping through  dictionaries involves a different approach as compared to lists and strings.
 As dictionaries are not index based, we need to use its built-in items() method as below:**

### Class Exercise 14

Create a dictionary named dict that stores stock tickers as keys and their prices as values:

{'AAPL':193.53, 'HP':24.16, 'MSFT':108.29, 'GOOG':1061.49}

Write a Python program that loops through the dictionary using .items() and prints each stock’s name and its price in the format:

Price of AAPL is 193.53

In [19]:
dict = {'AAPL':193.53, 'HP':24.16, 'MSFT':108.29, 'GOOG':1061.49}

for key, value in dict.items():
    print(f'Price of {key} is {value}')

Price of AAPL is 193.53
Price of HP is 24.16
Price of MSFT is 108.29
Price of GOOG is 1061.49


In [20]:
dict = {'AAPL':193.53, 'HP':24.16, 'MSFT':108.29, 'GOOG':1061.49}

for x, y in dict.items():
    print(f'Price of {x} is {y}')

Price of AAPL is 193.53
Price of HP is 24.16
Price of MSFT is 108.29
Price of GOOG is 1061.49


In [21]:
# If we execute dict.items(0 directly, it returns dict items in the form of tuples)
dict.items()

dict_items([('AAPL', 193.53), ('HP', 24.16), ('MSFT', 108.29), ('GOOG', 1061.49)])

### List Comprehensions

SYNTAX [expression **for** item in iterable]

**List comprehension is an elegant way to define and create a list in Python. It is used to create a new list from another sequence, just like a mathematical set notation in a single line. As we see in the Python code above, list comprehension starts and ends with square brackets to help us remember that the output will be a list.** 

### Class Exercise 15

Write a Python program that creates an empty list called square_list.<br>
Using a for loop with range(0, 10), compute the square of each number and use append() to add the result to the list.<br>
After each append, print the updated square_list.

In [22]:
square_list = []

for x in range(0, 10):
    square_list.append(x ** 2)
    print(square_list)

[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Class Exercise 16

Rewrite the logic of generating squares of numbers from 0 to 9 using list comprehension instead of a for loop.<br>
Create a list that contains x ** 2 for every x in range(0, 10).

In [23]:
# Now using List Comprehension
[x ** 2 for x in range(0,10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### Class Exercise 17

Filter positive numbers less than 20 that are divisible by both 2 and 3 using list comprehension instead of a for loop.<br>
Use range(0, 20) 

In [24]:
# We can have multiple condition to filter the output
# Have a list of all positive numbers less than 50 which are divisible by 2 and 3 both

[x for x in range(0,20) if x%2==0 if x%3==0] #% gives us remainder

[0, 6, 12, 18]

In [25]:
5 % 2

1

In [26]:
6 % 2

0

### Example of IF + ELSE in List Comprehension

In [27]:
labels = ["Even" if x % 2 == 0 else "Odd" for x in range(6)]
print(labels)

['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']


### Trading Signal Generator (BUY / SELL)

### Class Exercise 18

Create two lists named short_ma and long_ma that store short-term and long-term moving average values:

short_ma = [100, 102, 104, 106, 105, 103, 101]<br>
long_ma = [101, 101, 102, 103, 104, 104, 104]

Write a Python program that loops through both lists (starting from index 1) and prints:

“Buy signal” when short_ma crosses above long_ma

“Sell signal” when short_ma crosses below long_ma

“Hold” otherwise

In [28]:
short_ma = [100, 102, 104, 106, 105, 103, 101]
long_ma  = [101, 101, 102, 103, 104, 104, 104]

for i in range(1, len(short_ma)):      # start from 1 to compare today’s values with yesterday’s
    if short_ma[i-1] < long_ma[i-1] and short_ma[i] > long_ma[i]:
        print(f"Day {i}: Buy signal")
    elif short_ma[i-1] > long_ma[i-1] and short_ma[i] < long_ma[i]:
        print(f"Day {i}: Sell signal")
    else:
        print("Hold")

Day 1: Buy signal
Hold
Hold
Hold
Day 5: Sell signal
Hold


## zip() gives one pair at a time
A Loop takes one pair at a time<br>
We only convert it to a list, when we want to see all values together

### The zip() function - Iterable

In [29]:
company_names = ['Apple', 'Microsoft', 'Tesla']
tickers = ['AAPL', 'MSFT', 'TSLA']
z = zip(company_names, tickers)
print(z)

In [30]:
z_list = list(z)
print(z_list)

[('Apple', 'AAPL'), ('Microsoft', 'MSFT'), ('Tesla', 'TSLA')]


### Class Exercise 19

**Create three lists named price, ma_value, and rsi_value that store price, moving average, and RSI values for 20 periods:**

price = [102.5, 104.1, 103.8, 105.7, 107.2, 106.4, 108.9, 109.3, 110.1, 111.8,
112.4, 113.2, 114.0, 115.6, 116.8, 118.1, 117.5, 119.3, 120.0, 121.4]

ma_value = [101.8, 102.3, 102.9, 103.5, 104.2, 105.0, 105.8, 106.6, 107.4, 108.1,
108.9, 109.7, 110.3, 111.0, 111.8, 112.6, 113.2, 113.9, 114.7, 122.5]

rsi_value = [42, 45, 48, 52, 55, 58, 60, 64, 67, 70,
73, 69, 65, 62, 58, 55, 52, 49, 46, 43]

**Write a Python program that loops through these lists using zip() and prints:**

BUY when price > MA and RSI > 40

SELL when price < MA

HOLD in all other cases

Add logic to ensure:

Before the first BUY ever happens → output should be only BUY or None

After the first BUY → use normal BUY / SELL / HOLD behaviour

Store all signals inside a list named signals.

In [31]:
price = [100, 104.1, 103.8, 105.7, 107.2, 106.4, 108.9, 109.3, 110.1, 111.8,
         112.4, 113.2, 114.0, 115.6, 116.8, 118.1, 117.5, 119.3, 120.0, 121.4]
ma_value = [101.8, 102.3, 102.9, 103.5, 104.2, 105.0, 105.8, 106.6, 107.4, 108.1,
            108.9, 109.7, 110.3, 111.0, 111.8, 112.6, 113.2, 113.9, 114.7, 122.5]
rsi_value = [42, 45, 48, 52, 55, 58, 60, 64, 67, 70,
             73, 69, 65, 62, 58, 55, 52, 49, 46, 43]

In [32]:
import time

signals = [] # Where signals will be stored
in_position = False        # Means we have NOT bought yet, Initial State
first_buy_done = False     # Means NO BUY has happened ever, Initial State

for p, ma, rsi in zip(price, ma_value, rsi_value):

    buy_condition = (p > ma) and (rsi > 40)
    sell_condition = (p < ma)

    # CASE 1: If we have NEVER done any BUY yet
    if first_buy_done == False:

        # Check if BUY should happen for the first time
        if buy_condition == True:  
            position = "BUY"
            in_position = True
            first_buy_done = True   # First BUY has now happened

        else:
            position = None         # No HOLD allowed before first BUY

    # CASE 2: Normal BUY/SELL/HOLD logic after FIRST BUY is done
    else:

        # If BUY condition is true AND we are NOT already in a position
        if buy_condition == True and in_position == False:
            position = "BUY"
            in_position = True

        # If SELL condition is true AND we ARE in a position
        elif sell_condition == True and in_position == True:
            position = "SELL"
            in_position = False

        # In all other cases → HOLD
        else:
            position = "HOLD"

    print(f"Price:{p}  MA:{ma}  RSI:{rsi}  ->  {position}")
    signals.append(position)
    time.sleep(1)

Price:100  MA:101.8  RSI:42  ->  None
Price:104.1  MA:102.3  RSI:45  ->  BUY
Price:103.8  MA:102.9  RSI:48  ->  HOLD
Price:105.7  MA:103.5  RSI:52  ->  HOLD
Price:107.2  MA:104.2  RSI:55  ->  HOLD
Price:106.4  MA:105.0  RSI:58  ->  HOLD
Price:108.9  MA:105.8  RSI:60  ->  HOLD
Price:109.3  MA:106.6  RSI:64  ->  HOLD
Price:110.1  MA:107.4  RSI:67  ->  HOLD
Price:111.8  MA:108.1  RSI:70  ->  HOLD
Price:112.4  MA:108.9  RSI:73  ->  HOLD
Price:113.2  MA:109.7  RSI:69  ->  HOLD
Price:114.0  MA:110.3  RSI:65  ->  HOLD
Price:115.6  MA:111.0  RSI:62  ->  HOLD
Price:116.8  MA:111.8  RSI:58  ->  HOLD
Price:118.1  MA:112.6  RSI:55  ->  HOLD
Price:117.5  MA:113.2  RSI:52  ->  HOLD
Price:119.3  MA:113.9  RSI:49  ->  HOLD
Price:120.0  MA:114.7  RSI:46  ->  HOLD
Price:121.4  MA:122.5  RSI:43  ->  SELL


                         ┌─────────────────────────┐
                         │   Start Loop (zip)      │
                         │  p, ma, rsi = each row  │
                         └───────────┬─────────────┘
                                     │
                                     ▼
                         ┌─────────────────────────┐
                         │ Compute Conditions:     │
                         │ buy = (p > ma & rsi>40) │
                         │ sell = (p < ma)         │
                         └───────────┬─────────────┘
                                     │
                         ┌───────────▼────────────┐
                         │ first_buy_done == False│
                         └───────────┬────────────┘
                                     │Yes
                                     ▼
                       ┌──────────────────────────────┐
                       │ Is buy_condition True?        │
                       └───────────┬───────────────────┘
                                   │Yes
                                   ▼
                     ┌─────────────────────────────────────┐
                     │ position = BUY                      │
                     │ in_position = True                  │
                     │ first_buy_done = True               │
                     └─────────────────────────────────────┘
                                   │No (buy false)
                                   ▼
                     ┌─────────────────────────────────────┐
                     │ position = None                     │
                     │ (No HOLD allowed before first BUY)  │
                     └─────────────────────────────────────┘
                                   │
                                   ▼
                     ┌───────────────────────────────────┐
                     │            NEXT LOOP              │
                     └───────────────────────────────────┘


───────────────────────────────────────────────────────────────────
 AFTER FIRST BUY DONE
───────────────────────────────────────────────────────────────────

                         ┌─────────────────────────┐
                         │ first_buy_done == True  │
                         └───────────┬─────────────┘
                                     │Yes
                                     ▼
                     ┌─────────────────────────────────────────┐
                     │ Is buy_condition True AND in_position=0?│
                     └───────────┬─────────────────────────────┘
                                 │Yes
                                 ▼
                     ┌─────────────────────────────────────────┐
                     │ position = BUY                           │
                     │ in_position = True                       │
                     └─────────────────────────────────────────┘
                                 │No
                                 ▼
          ┌─────────────────────────────────────────────────────────┐
          │ Is sell_condition True AND in_position == True?         │
          └───────────┬─────────────────────────────────────────────┘
                      │Yes
                      ▼
          ┌─────────────────────────────────────────────────────────┐
          │ position = SELL                                          │
          │ in_position = False                                      │
          └──────────────────────────────────────────────────────────┘
                      │No
                      ▼
          ┌─────────────────────────────────────────────────────────┐
          │ position = HOLD                                          │
          └──────────────────────────────────────────────────────────┘



### Class Exercise 20

**Create two lists named short_ma and long_ma that store short-term and long-term moving average values:**<br>
short_ma = [100, 102, 104, 106, 105, 103, 101]<br>
long_ma  = [101, 101, 102, 103, 104, 104, 104]<br>
**Write a Python program that loops through both lists starting from index 1 and prints:**


“Buy signal” when short_ma crosses above long_ma


“Sell signal” when short_ma crosses below long_ma


“Hold” in all other cases


Use yesterday’s values (i-1) and today’s values (i) to detect the crossover.

In [36]:
short_ma = [100, 102, 104, 106, 105, 103, 101]
long_ma  = [101, 101, 102, 103, 104, 104, 104]

for i in range(1, len(short_ma)):      # start from 1 to compare today’s values with yesterday’s
    if short_ma[i-1] < long_ma[i-1] and short_ma[i] > long_ma[i]:
        print(f"Day {i}: Buy signal")
    elif short_ma[i-1] > long_ma[i-1] and short_ma[i] < long_ma[i]:
        print(f"Day {i}: Sell signal")
    else:
        print(f"Day {i}: Hold")

Day 1: Buy signal
Day 2: Hold
Day 3: Hold
Day 4: Hold
Day 5: Sell signal
Day 6: Hold
